# permissions for end users to edit selfnoderemediationconfigs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: selfnoderemediationconfig-editor-role
rules:
- apiGroups:
  - self-node-remediation.medik8s.io
  resources:
  - selfnoderemediationconfigs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - self-node-remediation.medik8s.io
  resources:
  - selfnoderemediationconfigs/status
  verbs:
  - get
